// BPS province codes: https://sirusa.web.bps.go.id/metadata/variabel/326536
export const INDONESIA_PROVINCES = [
  { code: "11", nameEn: "Aceh", nameId: "Aceh" },
  { code: "12", nameEn: "North Sumatra", nameId: "Sumatera Utara" },
  { code: "13", nameEn: "West Sumatra", nameId: "Sumatera Barat" },
  { code: "14", nameEn: "Riau", nameId: "Riau" },
  { code: "15", nameEn: "Jambi", nameId: "Jambi" },
  { code: "16", nameEn: "South Sumatra", nameId: "Sumatera Selatan" },
  { code: "17", nameEn: "Bengkulu", nameId: "Bengkulu" },
  { code: "18", nameEn: "Lampung", nameId: "Lampung" },
  { code: "19", nameEn: "Bangka Belitung Islands", nameId: "Kepulauan Bangka Belitung" },
  { code: "21", nameEn: "Riau Islands", nameId: "Kepulauan Riau" },
  { code: "31", nameEn: "Jakarta", nameId: "DKI Jakarta" },
  { code: "32", nameEn: "West Java", nameId: "Jawa Barat" },
  { code: "33", nameEn: "Central Java", nameId: "Jawa Tengah" },
  { code: "34", nameEn: "Yogyakarta", nameId: "DI Yogyakarta" },
  { code: "35", nameEn: "East Java", nameId: "Jawa Timur" },
  { code: "36", nameEn: "Banten", nameId: "Banten" },
  { code: "51", nameEn: "Bali", nameId: "Bali" },
  { code: "52", nameEn: "West Nusa Tenggara", nameId: "Nusa Tenggara Barat" },
  { code: "53", nameEn: "East Nusa Tenggara", nameId: "Nusa Tenggara Timur" },
  { code: "61", nameEn: "West Kalimantan", nameId: "Kalimantan Barat" },
  { code: "62", nameEn: "Central Kalimantan", nameId: "Kalimantan Tengah" },
  { code: "63", nameEn: "South Kalimantan", nameId: "Kalimantan Selatan" },
  { code: "64", nameEn: "East Kalimantan", nameId: "Kalimantan Timur" },
  { code: "65", nameEn: "North Kalimantan", nameId: "Kalimantan Utara" },
  { code: "71", nameEn: "North Sulawesi", nameId: "Sulawesi Utara" },
  { code: "72", nameEn: "Central Sulawesi", nameId: "Sulawesi Tengah" },
  { code: "73", nameEn: "South Sulawesi", nameId: "Sulawesi Selatan" },
  { code: "74", nameEn: "Southeast Sulawesi", nameId: "Sulawesi Tenggara" },
  { code: "75", nameEn: "Gorontalo", nameId: "Gorontalo" },
  { code: "76", nameEn: "West Sulawesi", nameId: "Sulawesi Barat" },
  { code: "81", nameEn: "Maluku", nameId: "Maluku" },
  { code: "82", nameEn: "North Maluku", nameId: "Maluku Utara" },
  { code: "91", nameEn: "West Papua", nameId: "Papua Barat" },
  { code: "92", nameEn: "Southwest Papua", nameId: "Papua Barat Daya" },
  { code: "94", nameEn: "Papua", nameId: "Papua" },
  { code: "95", nameEn: "South Papua", nameId: "Papua Selatan" },
  { code: "96", nameEn: "Central Papua", nameId: "Papua Tengah" },
  { code: "97", nameEn: "Highland Papua", nameId: "Papua Pegunungan" },
] as const;
