export const assistantCopy = {
  en: {
    open: "Open Gascomp Assistant", close: "Close chat", loading: "Loading your conversation…",
    ready: "Ready to help", offline: "The assistant is offline. You can contact our admin below.",
    paused: "The assistant is paused. You can contact our admin below.", unavailable: "The assistant is unavailable. You can contact our admin below.",
    waiting: "Waiting for a reply…", sending: "Sending…", message: "Your message", placeholder: "Ask about your Gascomp product…",
    send: "Send", retry: "Retry", error: "We could not update your conversation. Retry or contact our admin.",
    sendError: "We could not confirm your message. Retry the same message to check it safely.",
    newChat: "New chat", startingNewChat: "Starting…",
    newChatError: "We could not start a new chat. Your current conversation was kept. Please retry.",
    whatsapp: "Chat with admin on WhatsApp", history: "Conversation", you: "You", empty: "Send a product question to start.",
    privacy: "Please do not share passwords, payment details, or private documents. Chats are kept for approximately 30 days.",
    noContact: "Admin contact is not configured. Please use the website contact section.",
  },
  id: {
    open: "Buka Gascomp Assistant", close: "Tutup chat", loading: "Memuat percakapan Anda…",
    ready: "Siap membantu", offline: "Asisten sedang offline. Anda dapat menghubungi admin di bawah.",
    paused: "Asisten sedang dijeda. Anda dapat menghubungi admin di bawah.", unavailable: "Asisten belum tersedia. Anda dapat menghubungi admin di bawah.",
    waiting: "Menunggu jawaban…", sending: "Mengirim…", message: "Pesan Anda", placeholder: "Tanyakan tentang produk Gascomp Anda…",
    send: "Kirim", retry: "Coba lagi", error: "Percakapan tidak dapat diperbarui. Coba lagi atau hubungi admin.",
    sendError: "Pesan Anda belum dapat dikonfirmasi. Coba kirim ulang pesan yang sama untuk memeriksanya dengan aman.",
    newChat: "Percakapan baru", startingNewChat: "Memulai…",
    newChatError: "Percakapan baru belum dapat dibuat. Percakapan Anda saat ini tetap tersimpan. Silakan coba lagi.",
    whatsapp: "Chat dengan admin melalui WhatsApp", history: "Percakapan", you: "Anda", empty: "Kirim pertanyaan tentang produk untuk memulai.",
    privacy: "Jangan bagikan kata sandi, informasi pembayaran, atau dokumen pribadi. Chat disimpan sekitar 30 hari.",
    noContact: "Kontak admin belum diatur. Silakan gunakan bagian kontak di website.",
  },
} as const;
